openapi: 3.0.0
info:
  title: 湘大文库API
  description: 描述和测试湘大文库API
  version: 1.0.0
servers:
  -
    url: 'http://search.localhost'
    description: '本地 API 服务器'

tags:
  -
    name: search
    description: 搜索相关
  -
    name: update
    description: 更新数据相关
  -
    name: external
    description: 额外接口


paths:
  /search/{key}:
    get:
      tags:
        - search
      summary: 普通搜索
      description: 返回查询到的页面列表
      operationId: singleSearch
      parameters:
        -
          name: key
          in: path
          description: 要搜索的关键词/句
          required: true
          schema:
            type: string
            default: 关键字
      responses:
        '200':
          description: 返回查询到的结果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search'
  /search/{key}/{page}:
    get:
      tags:
        - search
      sammary: 分页搜索
      description: 返回根据关键字查询结果的指定页面
      operetionId: pageSearch
      parameters:
        -
          name: key
          in: path
          description: 搜索关键字
          required: true
          schema:
            type: string
            default: 关键字
        -
          name: page
          in: path
          description: 页码
          required: true
          schema:
            type: integer
            default: 0
  /update:
    post:
      tags:
        - update
      summary: 更新页面
      description: 更新页面存储
      operationId: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                keyword:
                  type: array
                  items:
                    type: string
                content:
                  type: string
                picurl:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
                intro:
                  type: string
                url:
                  type: string
                note:
                  type: string
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/update'

components:
  schemas:
    search:
      properties:
        code:
          type: integer
          description: api返回值
          example: 0
        msg:
          type: string
          description: 返回信息
          example: 查询成功
        data:
          type: object
          properties:
            total:
              type: string
              description: 结果总数
              example: 1
            max_score:
              type: number
              description: 最大匹配评分
              example: 0.2876821
            hits:
              type: object
              description: 查询结果集
              properties:
                _index:
                  type: string
                _type:
                  type: string
                  example: "webPage"
                _id:
                  type: string
                  example: "U3G_IWoBRObftyg5KFSP"
                _score:
                  type: number
                  example: 0.2876821
                _source:
                  type: object
                  properties:
                    title:
                      type: string
                      example: "我的测试"
                    keyword:
                      type: array
                      items:
                        type: string
                        example: [
                          "测试",
                          "更新"
                        ]
                    "tags":
                      type: string
                      example: [
                        "测试",
                        "我"
                      ]
                    intro:
                      type: string
                      example: "一个用于测试的样例数据"
                    content:
                      type: string
                      example: "测试测试测试一个测试有用的测试"
                    url":
                      type: string
                      example: "localhost/test"
                    picurl:
                      type: string
                      example: ""
                    note:
                      type: string
                      example: ""
    update:
      properties:
        code:
          type: integer
          description: api返回值
          example: 0
        msg:
          type: string
          description: 返回信息
          example: 查询成功